[project]
name = "rag-openrouter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.0.5",
    "langchain-text-splitters>=1.0.0",
    "openai>=2.7.2",
    "pinecone>=7.3.0",
    "pypdf>=6.2.0",
    "python-dotenv>=1.0.0",
    "rank-bm25>=0.2.2",
    "reportlab>=4.4.4",
    "scikit-learn>=1.7.2",
    "sentence-transformers>=5.1.2",
]
